### ISSUE TITLE
Error While Downloading Journal Articles

### ISSUE THREAD

**Issue by tfryed** [alexsands/coyote-badger#12]
Hello,

I am currently working on VOL101-1-IS-Bressman-Actual, and Coyote Badger is giving me an error when attempting to download journal articles. It is generating a "Failure" message for journal articles. I think CB is identifying that these journals exist in hein online, but it is unable to download them. Two examples are below:

100 Cornell L. Rev. 769 - Sunstein, Unanimity and Disagreement on the Supreme Court
CB Terminal output when attempting to pull this piece (which I have confirmed is available on Hein Online):

172.17.0.1 - - [16/Aug/2022 16:08:33] "POST /login?project=VOL101-1-IS-Bressman-Actual HTTP/1.1" 302 -
172.17.0.1 - - [16/Aug/2022 16:08:33] "GET /sources/VOL101-1-IS-Bressman-Actual HTTP/1.1" 200 -
172.17.0.1 - - [16/Aug/2022 16:09:08] "POST /sources/VOL101-1-IS-Bressman-Actual HTTP/1.1" 200 -
172.17.0.1 - - [16/Aug/2022 16:09:24] "GET /pull HTTP/1.1" 200 -
Timeout 15500.0ms exceeded while waiting for event "download"
=========================== logs ===========================
waiting for event "download"
============================================================
Error while downloading journal article

Piece - 71 Vand. L. Rev. 465 - Grove, The Origins (and Fragility) of Judicial Independence
CB Terminal Output when attempting to pull this piece (which is in Hein Online). 

72.17.0.1 - - [16/Aug/2022 16:10:04] "POST /pull HTTP/1.1" 200 -
172.17.0.1 - - [16/Aug/2022 16:11:14] "POST /sources/VOL101-1-IS-Bressman-Actual HTTP/1.1" 200 -
172.17.0.1 - - [16/Aug/2022 16:11:30] "GET /pull HTTP/1.1" 200 -
Timeout 15500.0ms exceeded while waiting for event "download"
=========================== logs ===========================
waiting for event "download"
============================================================
Error while downloading journal article
172.17.0.1 - - [16/Aug/2022 16:12:09] "POST /pull HTTP/1.1" 200 -

Coyote Badger can pull court cases and other files still, so this seems isolated to Journal Articles for now.

I am running on a MAC Airbook Apple M1. 

Please let me know if you need anymore information from me.

-Trey

**Comment by alexsands** [comment]
Hey Trey - my girlfriend graduated so I don't have access to a Duo account for Hein/Westlaw anymore. I can help debug this (some HTML probably changed or something) but will need to log in somehow.

Does it happen on all Journal articles? Or just certain ones?

Also I'm out of town until Sunday but can try to look at it after that.

**Comment by tfryed** [comment]
Looks like it was all journal articles in Bressman. I was able to download some other journal articles earlier in the week, though, so I'll rerun some of those again just to make sure it's not a Bressman specific thing.

**Comment by alexsands** [comment]
Issue was related to multiple Hein sources running back-to-back and resolved by spacing them out over time. Closing this issue for now, but please reopen if it continues to be an issue.
