### ISSUE TITLE
Login Issue Likely Due to Duo Update 

### ISSUE THREAD

**Issue by Agonz327** [alexsands/coyote-badger#14]
HI, 

I believe the update to the duo authentication system interface has broken the login. 

Whenever I try to log in, the command prompt reads "waiting for selector "#duo_iframe" to be visible" before eventually timing out. My login information is correct because when I try to sign in, I get the duo notification to approve the request, but CB still fails to log in to Hein.  This issue is present on both Mac & PC. 

**I should add that the specific issue (based on what I saw in the Watch Live feature) appears to be the fact that after approving the log in, the Duo prompt now asks if you want to trust the browser. Since no option is chosen, the request times out.

**Comment by tfryed** [comment]
Hi,

I am also seeing this issue. I have not changed my logins, but Coyote Badger is failing to log into Hein. Hein appears to be the only one of the three logins (hein, Westlaw, and SSRN) that fails. 

I am on MAC as well.

**Comment by alexsands** [comment]
Happy to take a look and fix this, but I don't have a login to test with unfortunately. Would either of you be willing to hop on a Zoom for 30 min / 1 hr to help debug? Feel free to email me instead of posting here.

**Comment by alexsands** [comment]
Okay this should be fixed in the [latest version (2.2.0)](https://github.com/alexsands/coyote-badger/releases/tag/v2.2.0) now! I'm going to close this for now, but if you test it out and its still not working, please reopen.
