### ISSUE TITLE
converter.py issue

### ISSUE THREAD

**Issue by TLR-RE** [alexsands/coyote-badger#2]
Josh,

I want to try using GitHub instead of email for logging issues, to make things easier for future editors to see. But to protect our authors' works, I will send attachments to you via email. I have run across an issue generating an inventory sheet, which I believe uses converter.py. The program skipped over FNs 4 and 10, and probably others, and we don't want it to do that. When you have a moment (not urgent) can you take a stab at understanding the logic behind converter.py? It would be great if we can identify what caused the program to skip over these two footnotes to correct it for future issues. I will send an email with more info. Thank you!

Thanks,
Emma

**Comment by alexsands** [comment]
It looks like the two citations, FNs 4 and 10, are being skipped because they contain "Id. at ###", which is a format filter that causes the citations to be ignored. If these citations shouldn't be ignored, the spot to start is here: https://github.com/alexsands/coyote-badger/blob/41e2a9340e012211b34a6fb512d7ab67cdc46caf/coyote_badger/converter.py#L89-L91

**Comment by alexsands** [comment]
By the way — Josh, I think the solution here is just to remove that rule and, in its place, check if the citation **_starts with_** "Id." (or some variant). That way we aren't throwing away citations that contain "Id." later on in the body, but it's safe to throw away ones that start with "Id." since those are obviously referencing a previous citation. So the fix should be just changing this one line: https://github.com/alexsands/coyote-badger/blob/41e2a9340e012211b34a6fb512d7ab67cdc46caf/coyote_badger/converter.py#L90 I'm happy to make the change, but I'll let you try and make a PR if you'd like. Just let me know.

**Comment by TLR-RE** [comment]
I think it's a little more complicated than that because even if the footnote starts with "Id. at XXX." it may contain full cites later on that we want to keep. Example: 

(FN 4). 141 S.Ct. 1183 (2021). Justices Thomas and Alito dissented. Id. at 1210-20. Early in the litigation, Google did X and the judge did Y. See Oracle Am., Inc. v. Google Inc., 810 F. Supp.2d 1002 (N.D. Cal. 2011) (Oracle I).

(FN Z). Id. at 1210-20. Early in the litigation, Google did X and the judge did Y. See Oracle Am., Inc. v. Google Inc., 810 F. Supp.2d 1002 (N.D. Cal. 2011) (Oracle I).

In both of these examples, we want to keep the Oracle Am. citation. I think right now the code recognizes separate citations when they're separated by ';' but not '.' -- might be difficult to get it to recognize the case where each citation is in its own sentence, since periods are used for other things (like id., e.g., i.e., etc...) I'll have to think about it some more.

**Comment by alexsands** [comment]
I see. So maybe we just do the footnote ONLY has "Id. at XXX" (or a variant)? E.g.:

**(FN A). 141 S.Ct. 1183 (2021). Justices Thomas and Alito dissented. Id. at 1210-20. Early in the litigation, Google did X and the judge did Y. See Oracle Am., Inc. v. Google Inc., 810 F. Supp.2d 1002 (N.D. Cal. 2011) (Oracle I).**
Saved, doesn't match the filter.

**(FN B). Id. at 1210-20. Early in the litigation, Google did X and the judge did Y. See Oracle Am., Inc. v. Google Inc., 810 F. Supp.2d 1002 (N.D. Cal. 2011) (Oracle I).**
Saved, doesn't match the filter.

**(FN C). Id. at 34**
Removed, matches the filter.

**(FN D). Id.**
Removed, matches the filter.

This would be pretty conservative, so the editors may have more extraneous citations that they'll have to remove/split up. But that's probably better than removing too much, right?

**Comment by alexsands** [comment]
Another alternative would be to not actually remove any citations. Instead we could have another column in the `Sources.xlsx` output called "Possible Removal?" that marks whether or not the program thinks it should be removed. We could also supply the justification as to why (e.g., "This citation was seen before in FN 20") in another column. Thoughts?

**Comment by ws9** [comment]
Jumping in here in case I can be helpful. You may already know this or have
this, but there is an old VBA script that may have the logic you are
looking for. Granted, it's nearly 20 years old at this point, so given
changes in the BB, it may need to be tweaked. And it's in VBA not python,
but the logic is there.

I've attached it.

Happy to help however I can.

All the best,
Warner

**Comment by TLR-RE** [comment]
Hi Warner!! So nice to see your name pop up today :) We have the script and I do think a future project for one of my Associate Editors should be comparing the script to the Python code and seeing what else we can/should add in for the inventory sheet creation process.

For now, Alex, I think the conservative approach you suggested is the way to go. We would rather have extraneous citations that need to be removed/split up than be missing key sources altogether. I don't want to add additional columns right now as it might confuse new members, and removing ids. manually takes no time at all (most of the time there's like 10 members doing the cleaning/de-duping, so they each have only ~20 rows).

So, if footnote ONLY has "Id. at XXX" OR if footnote ONLY has "Id.", then skip it. Otherwise, we'll keep all of it and manually delete.
