### ISSUE TITLE
Currently failing on M1 Macs due to playwright installation

### ISSUE THREAD

**Issue by alexsands** [alexsands/coyote-badger#6]
According to this playwright issue (https://github.com/microsoft/playwright-python/issues/791), it seems that installing playwright within Docker on M1 Macs is failing. This will prevent CB from working on Macs with Apple Silicon currently. 

Microsoft is working on publishing ARM-based packages: https://github.com/microsoft/playwright/issues/7723. Currently debugging to see if anything can be done in the meantime.

**Comment by alexsands** [comment]
I've added an issue to the playwright project (https://github.com/microsoft/playwright-python/issues/907) to track the progress on arm64 wheels. Hopefully those are added soon or an alternative is suggested.

**Comment by joshuagraham21** [comment]
Hey, Alex: 

I'll be sure to keep an eye on this. Is there anything that I can do in the mean time?

**Comment by alexsands** [comment]
@joshuagraham21 I actually got it to run on an Apple Silicon Mac last night. You can't do it with Docker, but you can do it manually in a different way. I'll write up the instructions later today in the README.

**Comment by joshuagraham21** [comment]
@alexsands Emma asked me to create a new inventory sheet tomorrow. But, while I have a mac with an intel processor and the issue seems to be confined to apple silicon macs. After spending some time trying to figure it out on my own, I think it's time I reached out for help. Do you have any ideas for a work around? Should I try to get my hands on a PC and run CB that way? Thanks!

**Comment by alexsands** [comment]
CB should work fine right now with Intel Mac, although I did notice Hein changed their sign in URL. I have the fix for both that and to make CB run on Apple Silicon Macs, just need to test it once more on an M1. I should be able to do that tonight and have the new version posted.

**Comment by alexsands** [comment]
Version 1.1.0 is out now. It supports Apple Silicon when run using the [Development instructions](https://github.com/alexsands/coyote-badger#development). It also runs in Docker if all you need is the Converter (generating a `Source.xlsx` sheet), but if you need to pull sources it throws an error when you try to log in. So close! I'll eventually get the whole thing working in Docker, I'm just trying to figure out what might be causing this last error.

Continues to work fine on Macs with Intel processors.
