### ISSUE TITLE
playwright._impl._api_types.Error: Protocol error (Browser.getVersion): Browser closed.

### ISSUE THREAD

**Issue by TLR-RE** [alexsands/coyote-badger#9]
Trying to get the new Research Editor set up running CB. It has worked for journals and cases on his computer but it's having trouble with websites, and then after about 50 or so sources it sets them all to "In progress" and stops running. I thought it may have been an issue with an adblocker in Chrome that he has since disabled, but that didn't seem to change things. He also uses a Macbook Air in case processing power might be an issue. Do you think either of these things could throw that error? I attachted the terminal output as well.

FYI I am still able to run everything smoothly on my Macbook Pro!

[Terminal playwright error.docx](https://github.com/alexsands/coyote-badger/files/8127071/Terminal.playwright.error.docx)

**Comment by alexsands** [comment]
Can you please go to `Apple Logo (top left of screen)` > `About This Mac` > `System Report...` and copy/paste these details from the `Hardware` tab:

- Model Name:
- Model Identifier:
- Chip:
- Total Number of Cores:
- Memory:

Could you please also upload or email me the source list that has this issue? 

The Chrome that he is opening to disable adblocker likely isn't the one that CB is using. CB uses a specific, hidden browser binary that isn't the same as the one you have installed and use normally.

Once I have that ^, I'll take a look later tonight!

**Comment by alexsands** [comment]
Also, reason I need that stuff from the `Hardware` tab is because I'm guessing that his laptop is a MacBook Air with an Apple Silicon M1 chip. If so, I have one now too, so I can finally make this work on M1.

**Comment by TLR-RE** [comment]
Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	7429.41.5
  OS Loader Version:	7429.41.5
  Serial Number (system):	FVFG70T6Q6LR
  Hardware UUID:	56E2DB8D-75AC-56CB-9A80-33A0FD2CCA79
  Provisioning UDID:	00008103-001218D80C40801E
  Activation Lock Status:	Enabled

Also, attached is the Robertson source sheet that I was using when I got these errors, along with the Terminal information from when I ran into the issues.

Please let me know if you need more info from me!

BEst,
Trey

**Comment by alexsands** [comment]
Thanks Trey! It looks like you have an M1 Mac, so CB won't work using Docker yet (see #6). You can run it without Docker in the meantime, if you really need to (see my comment [here](https://github.com/alexsands/coyote-badger/issues/6#issuecomment-926331528)).

If you don't need it immediately, I have an M1 mac myself now, so I'll get CB working on M1 w/ Docker over the next couple of days. Will keep you posted!

**Comment by TLR-RE** [comment]
That is fantastic! I have a Windows desktop which I will use instead while you get this updated. Thank you so much for the help!

Best,
Trey
